### ISSUE TITLE
[Question] First byte drastic performance decrease

### ISSUE THREAD

**Issue by jkujawski** [spatie/server-side-rendering#18]
In e-commerce site that heavily uses Vue as a javascript framework we've faced the problem of generating full source for SEO purposes.

We have decided to try and go with SSR.

Unfortunately after enabling SSR performance of website drastically decreased.
Without SSR we have ~400ms response time (first byte) for a website that has to analyze ~250k offers, filters, and other stuff. Once we enable SSR first byte jumps to around ~1.2s. Which unfortunately is not acceptable for the SEO purposes.

We use Node engine, which basically means that on each request new node instance is started.

We can of course try to apply caching, and not remove generated .js file for some time and solve this issue for uses, but this won't solve the problem for robots. Because if a page is not cached, then first byte will still be around ~1.2s

Any ideas what might be done to improve performance of SSR?

**Comment by robinvdvleuten** [comment]
What I've done to increase performance is to wrap the Node.js renderer around a custom caching class ([webstronauts/laravel-liftoff/app/Ssr/Engines/Cached.php](https://github.com/webstronauts/laravel-liftoff/blob/master/app/Ssr/Engines/Cached.php)). it uses the md5 hash of the script as caching key, so any dynamic context is taken into account.

**Comment by sebastiandedeyne** [comment]
First of all, thanks for the feedback! This is exactly the reason why this package isn't tagged 1.0 yet, because the tradeoffs are still a bit unknown and I haven't put a lot of thought in performance yet.

A while ago I came across this library: https://github.com/chancedickson/isorender-node

Instead of starting up a new Node process in every request, something similar to the Isorender package would allow you to spin up a Node process in the background, and commuicate with it via `localhost`. I think this would be a huge perf boost compared to the basic Node implementation supplied here.

It should be possible to write a custom `Engine` implementation that can communicate with an external process. I'd love to have this in the package at some point (maybe with the required JS for the process included instead of relying on a third party here), but haven't gotten the chance to experiment with this yet.

**Comment by jkujawski** [comment]
Thanks @robinvdvleuten @sebastiandedeyne 

We will try to investigate isorender-node.

As for cache, of course we are going to use it. But at this point we are mostly focused on the first byte of first page hit. Because there's a chance our users won't find every landing page, and google bot while parsing the page will for sure.

I'll let you know once we have any findings regarding the isorender-node.

**Comment by sebastiandedeyne** [comment]
> As for cache, of course we are going to use it. But at this point we are mostly focused on the first byte of first page hit. Because there's a chance our users won't find every landing page, and google bot while parsing the page will for sure.

On my personal site I run a crawler over all pages after every deploy. Totally different project scale of course, but if this is also an issue cache warming could also give a helping hand!

https://github.com/sebastiandedeyne/sebastiandedeyne.com/blob/470017a2acfe1ccbb581aec9b80abc6e1a47669f/app/Console/Commands/WarmCommand.php

**Comment by jkujawski** [comment]
@sebastiandedeyne we are currently discussing this approach internally. Unfortunately we have like hunred of thousands of landing pages. Or more. Warming cache in this case will be extremaly difficult and time consuming.

**Comment by sebastiandedeyne** [comment]
Gonna close this. Feel free to continue the discussion!

**Comment by joshhornby** [comment]
@robinvdvleuten The link you posted in [this comment](https://github.com/spatie/server-side-rendering/issues/18#issuecomment-399126666) has stopped working. Can you please share your caching code in this issue?

Thanks

**Comment by dyegonery** [comment]
I'm also facing this issue currently. Have you tried using V8Js as the engine? Is the performance with V8Js also an issue?
